export const RECEIVE_PEOPLE = 'RECEIVE_PEOPLE';
export const REQUEST_PEOPLE = 'REQUEST_PEOPLE';
export const SELECT_PERSON = 'SELECT_PERSON';
export const SAVE_PERSON_REQUESTED = 'SAVE_PERSON_REQUESTED';
export const SAVE_PERSON_REJECTED = 'SAVE_PERSON_REJECTED';
export const SAVE_PERSON_FULFILLED = 'SAVE_PERSON_FULFILLED';